// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rabbot.Database;

namespace Rabbot.Database.Migrations
{
    [DbContext(typeof(RabbotContext))]
    [Migration("20200407152210_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rabbot.Database.Rabbot.AttackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<DateTime>("EndTime");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("MessageId");

                    b.Property<ulong>("TargetId");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("TargetId");

                    b.HasIndex("UserId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.BadWordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BadWord");

                    b.Property<ulong>("GuildId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("BadWords");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.CombiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Accepted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<ulong>("CombiUserId");

                    b.Property<DateTime>("Date");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong?>("MessageId");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CombiUserId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Combis");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.CurrentDayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.ToTable("CurrentDay");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.EasterEventEntity", b =>
                {
                    b.Property<ulong>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CatchTime");

                    b.Property<DateTime?>("DespawnTime");

                    b.Property<DateTime>("SpawnTime");

                    b.Property<ulong?>("UserId");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("EasterEvents");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BonusPercent");

                    b.Property<string>("Name");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.FeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Attacks")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("CombiExp")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Eggs")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Exp")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<bool>("GainExp")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int>("Gewinn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Goats")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<ulong>("GuildId");

                    b.Property<bool>("HasLeft")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastDaily");

                    b.Property<DateTime>("LastMessage");

                    b.Property<bool>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Loses")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Spins")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("StreakLevel")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("TodaysWords")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("TotalWords")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Trades")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<ulong>("UserId");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.GuildEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("BotChannelId");

                    b.Property<string>("GuildName");

                    b.Property<bool>("Level")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<ulong?>("LevelChannelId");

                    b.Property<bool>("Log")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<ulong?>("LogChannelId");

                    b.Property<ulong?>("NotificationChannelId");

                    b.Property<bool>("Notify")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<ulong?>("StreamChannelId");

                    b.Property<bool>("Trash")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<ulong?>("TrashChannelId");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.InventoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Durability")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<int>("FeatureId");

                    b.Property<int>("ItemId");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventorys");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Atk");

                    b.Property<int>("Def");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.MusicrankEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("Seconds")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0ul);

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Musicranks");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.MutedUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Duration");

                    b.Property<ulong>("GuildId");

                    b.Property<string>("Roles");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("MutedUsers");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.NamechangeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("NewName")
                        .IsUnicode(true);

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Namechanges");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.OfficialPlayerEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("Playercount");

                    b.HasKey("Id");

                    b.ToTable("OfficialPlayers");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.PotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Goats")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.RandomAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.HasKey("Id");

                    b.ToTable("RandomAnswers");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.RemnantsPlayerEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("Playercount");

                    b.HasKey("Id");

                    b.ToTable("Remnantsplayers");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.SongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.StreamEntity", b =>
                {
                    b.Property<ulong>("StreamId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("Title");

                    b.Property<ulong>("TwitchUserId");

                    b.HasKey("StreamId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.UserEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsUnicode(true);

                    b.Property<bool>("Notify")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.WarningEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Counter");

                    b.Property<ulong>("GuildId");

                    b.Property<DateTime>("Until");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.YouTubeVideoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VideoId");

                    b.Property<string>("VideoTitle");

                    b.HasKey("Id");

                    b.ToTable("YouTubeVideos");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.AttackEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Attacks")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "Target")
                        .WithMany("AttackTargets")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("AttackUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.BadWordEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("BadWords")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.CombiEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "CombiUser")
                        .WithMany("CombiCombiUsers")
                        .HasForeignKey("CombiUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Combis")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("CombiUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.EasterEventEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("EasterEvents")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.FeatureEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Features")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("Features")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.InventoryEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.FeatureEntity", "Feature")
                        .WithMany("Inventory")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.ItemEntity", "Item")
                        .WithMany("Inventory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.MusicrankEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Musicranks")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("Musicranks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.MutedUserEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("MutedUsers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("MutedUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.NamechangeEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("Namechanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.PotEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Pots")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("Pots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.RoleEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rabbot.Database.Rabbot.WarningEntity", b =>
                {
                    b.HasOne("Rabbot.Database.Rabbot.GuildEntity", "Guild")
                        .WithMany("Warnings")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rabbot.Database.Rabbot.UserEntity", "User")
                        .WithMany("Warnings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
